/**
 * All user-visible text in Hebrew — RTL layout
 * Edit this file to update any UI text across the application.
 */
export const TEXT = {
  app: {
    name: 'PowerTracker',
    tagline: 'עקוב אחר כוחך',
    loading: 'טוען...',
    error: 'שגיאה',
    retry: 'נסה שוב',
    cancel: 'ביטול',
    save: 'שמור',
    delete: 'מחק',
    edit: 'ערוך',
    add: 'הוסף',
    close: 'סגור',
    back: 'חזור',
    next: 'הבא',
    done: 'סיום',
    confirm: 'אישור',
    yes: 'כן',
    no: 'לא',
    optional: 'אופציונלי',
    required: 'שדה חובה',
    search: 'חיפוש',
    noResults: 'לא נמצאו תוצאות',
    offline: 'אין חיבור לאינטרנט',
    syncing: 'מסנכרן...',
    syncComplete: 'הנתונים סונכרנו',
  },

  nav: {
    dashboard: 'בית',
    workout: 'אימון',
    analytics: 'סטטיסטיקות',
    social: 'חברתי',
    profile: 'פרופיל',
    calendar: 'לוח שנה',
  },

  auth: {
    login: 'התחברות',
    register: 'הרשמה',
    logout: 'התנתקות',
    email: 'אימייל',
    password: 'סיסמה',
    confirmPassword: 'אישור סיסמה',
    username: 'שם משתמש',
    loginButton: 'כניסה',
    registerButton: 'צור חשבון',
    noAccount: 'אין לך חשבון?',
    hasAccount: 'כבר יש לך חשבון?',
    forgotPassword: 'שכחת סיסמה?',
    loginError: 'שגיאה בהתחברות. בדוק פרטים.',
    registerError: 'שגיאה בהרשמה. נסה שנית.',
    passwordMismatch: 'הסיסמאות אינן תואמות',
    weakPassword: 'סיסמה חייבת להכיל לפחות 6 תווים',
    invalidEmail: 'כתובת אימייל לא תקינה',
    usernameTaken: 'שם המשתמש תפוס',
    emailTaken: 'אימייל כבר רשום',
    welcome: 'ברוך הבא',
    welcomeBack: 'ברוך שובך',
  },

  dashboard: {
    title: 'לוח בקרה',
    greeting: 'שלום',
    totalWorkouts: 'סה"כ אימונים',
    thisWeek: 'השבוע',
    streak: 'רצף ימים',
    days: 'ימים',
    calories: 'קלוריות',
    distance: 'מרחק',
    duration: 'משך',
    recentWorkouts: 'אימונים אחרונים',
    noWorkouts: 'עדיין אין אימונים. התחל את הראשון!',
    startWorkout: 'התחל אימון',
    weeklyGoals: 'יעדים שבועיים',
    aiCoach: 'מאמן AI',
    personalRecords: 'שיאים אישיים',
  },

  workout: {
    new: 'אימון חדש',
    edit: 'ערוך אימון',
    resume: 'המשך אימון',
    types: {
      running: 'ריצה',
      walking: 'הליכה',
      gym: 'חדר כושר',
    },
    categories: {
      legs: 'רגליים',
      chest_back: 'חזה וגב',
      arms_shoulders: 'ידיים וכתפיים',
      push: 'דחיפה',
      pull: 'משיכה',
      custom: 'מותאם אישית',
    },
    distance: 'מרחק (ק"מ)',
    duration: 'משך (דקות)',
    intensity: 'עוצמה',
    intensityLevels: ['קל מאוד', 'קל', 'בינוני', 'קשה', 'קשה מאוד'],
    calories: 'קלוריות שנשרפו',
    pace: 'קצב ממוצע',
    paceUnit: 'דקות לק"מ',
    notes: 'הערות',
    notesPlaceholder: 'הוסף הערות לאימון...',
    visibility: {
      title: 'פרטיות',
      private: 'פרטי',
      friends: 'לחברים',
    },
    save: 'שמור אימון',
    delete: 'מחק אימון',
    deleteConfirm: 'האם אתה בטוח שברצונך למחוק אימון זה?',
    saved: 'האימון נשמר!',
    deleted: 'האימון נמחק',
    autoSave: 'נשמר אוטומטית',
    saving: 'שומר...',
    draft: 'טיוטה',
    draftFound: 'נמצאה טיוטת אימון',
    draftResume: 'המשך אימון',
    draftDiscard: 'מחק טיוטה',
    gymCategory: 'קטגוריית האימון',
    customCategory: 'קטגוריה מותאמת אישית',
    customCategoryName: 'שם הקטגוריה',
    addCustomCategory: 'הוסף קטגוריה',
    chooseType: 'בחר סוג אימון',
    chooseCategory: 'בחר קטגוריה',
    startTime: 'שעת התחלה',
    endTime: 'שעת סיום',
  },

  exercises: {
    title: 'תרגילים',
    add: 'הוסף תרגיל',
    addNew: 'תרגיל חדש',
    name: 'שם התרגיל',
    namePlaceholder: 'לדוגמה: לחיצת חזה',
    search: 'חפש תרגיל',
    sets: 'סטים',
    addSet: 'הוסף סט',
    set: 'סט',
    weight: 'משקל (ק"ג)',
    reps: 'חזרות',
    totalVolume: 'נפח כולל',
    noExercises: 'לא הוספת תרגילים עדיין',
    recentlyUsed: 'בשימוש לאחרונה',
    custom: 'תרגיל מותאם אישית',
    image: 'תמונת תרגיל',
    uploadImage: 'העלה תמונה',
    removeImage: 'הסר תמונה',
    deleteExercise: 'מחק תרגיל',
    deleteSet: 'מחק סט',
  },

  analytics: {
    title: 'סטטיסטיקות',
    overview: 'סקירה כללית',
    running: 'ריצה',
    gym: 'חדר כושר',
    weekly: 'שבועי',
    monthly: 'חודשי',
    allTime: 'כל הזמן',
    totalDistance: 'מרחק כולל',
    totalWorkouts: 'סה"כ אימונים',
    avgPace: 'קצב ממוצע',
    avgDuration: 'משך ממוצע',
    workoutFrequency: 'תדירות אימונים',
    paceProgress: 'שיפור קצב',
    strengthProgress: 'שיפור כוח',
    caloriesBurned: 'קלוריות שנשרפו',
    workoutsByType: 'אימונים לפי סוג',
    streak: 'רצף',
    currentStreak: 'רצף נוכחי',
    longestStreak: 'רצף ארוך ביותר',
    personalRecords: 'שיאים אישיים',
    longestRun: 'הריצה הארוכה ביותר',
    fastestPace: 'הקצב המהיר ביותר',
    heaviestLift: 'המשקל הכבד ביותר',
    highestVolume: 'הנפח הגבוה ביותר',
    km: 'ק"מ',
    min: 'דק׳',
    kg: 'ק"ג',
  },

  social: {
    title: 'חברתי',
    friends: 'חברים',
    addFriend: 'הוסף חבר',
    friendRequests: 'בקשות חברות',
    pendingRequests: 'בקשות ממתינות',
    searchUsers: 'חפש משתמשים',
    searchPlaceholder: 'חפש לפי שם משתמש...',
    sendRequest: 'שלח בקשה',
    accept: 'אשר',
    reject: 'דחה',
    noFriends: 'עדיין אין חברים. חפש משתמשים!',
    friendSince: 'חברים מאז',
    workoutsFeed: 'אימוני חברים',
    noFeedItems: 'אין אימונים לתצוגה',
    comments: 'תגובות',
    addComment: 'הוסף תגובה...',
    commentButton: 'שלח',
    leaderboard: 'לוח מובילים',
    leaderboards: {
      title: 'לוח מובילים',
      mostWorkouts: 'הכי הרבה אימונים',
      longestStreak: 'הרצף הארוך ביותר',
      mostDistance: 'המרחק הרב ביותר',
      thisWeek: 'השבוע',
    },
    requestSent: 'בקשת חברות נשלחה!',
    requestAccepted: 'בקשת חברות אושרה!',
    requestRejected: 'בקשה נדחתה',
  },

  calendar: {
    title: 'לוח שנה',
    today: 'היום',
    noWorkout: 'אין אימון',
    workoutDays: 'ימי אימון',
    streakIndicator: 'רצף',
    months: [
      'ינואר', 'פברואר', 'מרץ', 'אפריל', 'מאי', 'יוני',
      'יולי', 'אוגוסט', 'ספטמבר', 'אוקטובר', 'נובמבר', 'דצמבר',
    ],
    days: ['א׳', 'ב׳', 'ג׳', 'ד׳', 'ה׳', 'ו׳', 'ש׳'],
  },

  profile: {
    title: 'פרופיל',
    editProfile: 'ערוך פרופיל',
    username: 'שם משתמש',
    email: 'אימייל',
    avatar: 'תמונת פרופיל',
    uploadAvatar: 'העלה תמונה',
    weeklyGoals: 'יעדים שבועיים',
    workoutsPerWeek: 'אימונים בשבוע',
    runningDistance: 'מרחק ריצה שבועי (ק"מ)',
    gymSessions: 'אימוני כושר בשבוע',
    saveGoals: 'שמור יעדים',
    goalsSaved: 'היעדים נשמרו!',
    settings: 'הגדרות',
    darkMode: 'מצב כהה',
    notifications: 'התראות',
    language: 'שפה',
    about: 'אודות',
    version: 'גרסה',
  },

  aiCoach: {
    title: 'מאמן AI',
    greeting: 'שלום! אני המאמן שלך.',
    tips: {
      rest: 'אתה צריך מנוחה! ישנת 3 ימים רצופים. קח יום חופש.',
      overtraining: 'זהירות! זיהיתי סימני אימון יתר. הפחת עוצמה.',
      consistency: 'כל הכבוד על הקביעות שלך! המשך כך.',
      progressiveOverload: 'הגיע הזמן להגדיל משקלים! נסה להוסיף 2.5 ק"ג.',
      beginnerAdvice: 'התחל בהדרגה. עדיפות ליציבות על פני עוצמה.',
      cardioBalance: 'שלב ריצה עם אימוני כוח לתוצאות מיטביות.',
      hydration: 'זכור לשתות מים לפני ואחרי האימון.',
    },
    recommendations: 'המלצות לאימון',
    noRecommendations: 'לא נמצאו המלצות. המשך לאמן!',
  },

  pwa: {
    installTitle: 'התקן את PowerTracker',
    installMessage: 'הוסף את האפליקציה למסך הבית לגישה מהירה!',
    installButton: 'התקן',
    installDismiss: 'לא עכשיו',
    offlineTitle: 'עובד במצב אופליין',
    offlineMessage: 'נתונים יסונכרנו בחזרה לאינטרנט',
  },

  errors: {
    generic: 'אירעה שגיאה. נסה שוב.',
    network: 'שגיאת רשת. בדוק חיבור לאינטרנט.',
    notFound: 'הדף לא נמצא.',
    unauthorized: 'אין לך הרשאה.',
    saveFailed: 'שמירה נכשלה. נסה שוב.',
    loadFailed: 'טעינה נכשלה. נסה שוב.',
    deleteFailed: 'מחיקה נכשלה.',
    uploadFailed: 'העלאה נכשלה.',
  },
} as const

export type TextKey = typeof TEXT
